### ISSUE TITLE
国内打不开

### ISSUE THREAD

**Issue by xieyouliang** [WanderingQuantum/qqsganalysis#1]
这个CND国内用不了能换成国内能用的吗？ 现在都打不开了
![微信图片_20220525163550](https://user-images.githubusercontent.com/37286954/170219162-199ae044-6f23-49a2-a013-c524a513cefa.png)
![微信图片_20220525163555](https://user-images.githubusercontent.com/37286954/170219168-3099d539-d97f-4ffd-8f67-9a51f8912c41.png)

**Comment by WanderingQuantum** [comment]
感谢提醒，jsdelivr经常挂，我已经将CDN的文件转到了本地。
