### ISSUE TITLE
基础状态表中的未知字段分析

### ISSUE THREAD

**Issue by wu-yafeng** [WanderingQuantum/qqsganalysis#4]
第六列的含义：
表示此基础状态的ICON标识符，此标识符的用途是在玩家的状态栏里的图标code。

下图是使用JS心法“玉石俱焚”时内存里的数据

![~{Y 9E8HUUQ}M$UFC }V1Z1](https://user-images.githubusercontent.com/25654404/192154516-ffffcc30-0993-403e-bdda-b2d75dffe839.png)

图中的汇编是GetDotInfo函数中的子过程，其中edx的值为0xC。

![image](https://user-images.githubusercontent.com/25654404/192154610-25d7e3d3-8244-4782-b4fa-59b699619d69.png)

其中 thiscall v14 + 0x4C8 跳转的地址为图1的汇编代码所在位置。最终图1所设置的值返回到了 GetDotInfo 函数中，并推送到了LUA栈的名为 “PicName” 的字段。

所以可以确定第六列为图片id

**Comment by WanderingQuantum** [comment]
非常感谢你的分析，已在基础状态数据表中对第六列做了标注。
