### ISSUE TITLE
地图表中的AG列含义分析

### ISSUE THREAD

**Issue by wu-yafeng** [WanderingQuantum/qqsganalysis#6]
测试背景：
玩家站在地图“吴郡西郊”，查表可得地图的MapId=14=0xE

该地图的数值在内存的位置在 MapInfo* = [[[[[[[[[[0x120352c]+0xC]+0x48+0x4]]+0x4]+0x4]+0x4]+0x8]+0x8]+0x10]。

结构大致为
``` cpp
struct MapInfo {
   int unknown[0x9C/4];
   int MapAttr;
};

```

其中0x9c的值为数值表的AG列。

在此内存区域新增硬件访问断点，在游戏中开启自动打怪，命中该断点。一路往上追，找到使用该值的汇编代码

![image](https://user-images.githubusercontent.com/25654404/193464855-6a06894e-e407-4a77-a476-ad6dce4881af.png)

在后续的逻辑中弹窗文本 “00F3097C 当前地图不可使用自动打怪！”

可得该字段表示地图的属性：其中 (MapInfo ->MapAttr & 0x1000000)!=0 表示该地图是可自动打怪的。

说明该字段要么是可表示8种地图属性（16进制），要么是表示32种地图属性（2进制）。

由于吴郡西郊的值是 0x02000200 = 33554944

说明该值是二进制的位运算。

**Comment by wu-yafeng** [comment]
通过查地图表可发现霸王城是不可自动打怪的地图，因为该地图的MapAttr=16777216=0x100000，刚好和0x1000000做“与运算”为0

**Comment by wu-yafeng** [comment]
(MapInfo ->MapAttr & 0x2)!=0 表示该地图是存在特权保护状态的地图

**Comment by WanderingQuantum** [comment]
吴郡西郊的AG列值为33554944=0x02000200，(0x02000200 & 0x01000000) == 0；而霸王城的AG列值为16777216=0x01000000，(0x01000000 & 0x01000000) != 0。所以应该是(AG & 0x01000000) == 0的表示可以自动打怪，而(AG & 0x01000000) != 0的表示不可自动打怪？

(AG & 0x2) != 0 表示该地图是存在特权保护状态的地图应该没问题。

**Comment by wu-yafeng** [comment]
> 吴郡西郊的AG列值为33554944=0x02000200，(0x02000200 & 0x01000000) == 0；而霸王城的AG列值为16777216=0x01000000，(0x01000000 & 0x01000000) != 0。所以应该是(AG & 0x01000000) == 0的表示可以自动打怪，而(AG & 0x01000000) != 0的表示不可自动打怪？
> 
> (AG & 0x2) != 0 表示该地图是存在特权保护状态的地图应该没问题。

对的，应该是(AG & 0x01000000) == 0的表示可以自动打怪，而(AG & 0x01000000) != 0的表示不可自动打怪 我弄反了

**Comment by WanderingQuantum** [comment]
好的，我已将这些内容加到[页面中](https://www.qqsganalysis.cn/#/%E5%8E%9F%E5%A7%8B%E8%A7%A3%E5%8C%85%E6%95%B0%E6%8D%AE?id=%e5%9c%b0%e5%9b%be%e6%95%b0%e6%8d%aemapdatatxt%ef%bc%88%e5%88%86%e6%9e%90%e8%80%85%ef%bc%9awu-yafeng%ef%bc%8c%e8%a7%81issue6%ef%bc%89)并标明了出处，非常感谢！

**Comment by heartwxmddd** [comment]
大佬，我想问下那个数值研究里的伤害公式（我是点那个作者链接跳转到github的，），作为系数的大写的ABCDEF，代表什么意思啊？
