### ISSUE TITLE
物品表K列的含义

### ISSUE THREAD

**Issue by wu-yafeng** [WanderingQuantum/qqsganalysis#7]
表示该物品可使用的目标对象：

**Comment by wu-yafeng** [comment]
H列的含义：
特性标志位

& 1 = 不可销毁
& 0x2000000 = 不可丢弃
& 2 = 不可与玩家交易
< 0 = 不可与NPC交易
& 4 = 不可存仓
& 8 = 离线消失
& 16 = 任务道具
& 0x400 = 不可使用

AO 列 = 标志位2
& 0x20 = 不可存公仓
& 0x40 = 不可存私仓
& 0x80 = 限特定关系交易


还有一些红名是否可以使用的字段、性别限制的字段、是否展示性别限制的字段、职业限制、是否展示职业限制、等级限制、物品的品质、名称的颜色、图标、是否可以放置、能否打孔、打孔数等等

**Comment by wu-yafeng** [comment]
E列表示含义：性别限制
如255表示的十六进制为0xFF, 运算 (0xFF & (1 | 2)) != 0  说明无性别限制
0xFF & 1 != 0  男性可用
0xFF & 2 != 0 女性可用

**Comment by Aconment** [comment]
看了下web端，物品数据，在线数据过大{很抱歉，无法在 Excel Online 中打开工作簿，因为它超出了 25 MB 文件大小限制}，打不开页面内容，建议分割显示。

**Comment by wu-yafeng** [comment]
V列表示物品的类型，此类型影响了物品的使用的校验逻辑。
下面是几种值的校验逻辑的按理

1. /C25您的在线总时间累计低于/C33%d/C25分钟，不能使用[/C33%s/C25]
5. /C28当前效果/C46%s/C28将被替换，您确定使用/C46%s/C28?
6. /C25您当前所在地图无法进行传送.
8. /C28使用该道具后,将清除您所有的副职业资料,您确定使用?
9. /C25您没有私人仓库使用权限 或 没有启用私人仓库,请购买相应权限并启用后,才能使用/C46%s
15、43、67. /C28您需要/C46%s/C28才能打开/C46%s/C28获得珍稀物品

**Comment by WanderingQuantum** [comment]
非常感谢！我已将这些内容加到[页面中](https://www.qqsganalysis.cn/#/%E5%8E%9F%E5%A7%8B%E8%A7%A3%E5%8C%85%E6%95%B0%E6%8D%AE?id=%e7%89%a9%e5%93%81%e6%95%b0%e6%8d%aeitemdatatxt%ef%bc%88%e5%88%86%e6%9e%90%e8%80%85%ef%bc%9awu-yafeng%ef%bc%8c%e8%a7%81issue7%ef%bc%89)并标明了出处，如果有修正或补充可以随时提出。

**Comment by WanderingQuantum** [comment]
> 看了下web端，物品数据，在线数据过大{很抱歉，无法在 Excel Online 中打开工作簿，因为它超出了 25 MB 文件大小限制}，打不开页面内容，建议分割显示。

已将表格进行分割，现在应该可以在线打开了，同时可以到网盘中直接下载Excel表格本地打开。
