### ISSUE TITLE
有关太极清灵术可解除的异常状态算法

### ISSUE THREAD

**Issue by wu-yafeng** [WanderingQuantum/qqsganalysis#8]
太极清灵术的主要数值1的值为 5507666

假设玩家所拥有的异常状态大类为A。是否可被太极清灵术清除的算法为：

((1<<(A&31))&5507666) != 0

**Comment by wu-yafeng** [comment]
补充说明：大类A需要右移5位获得 5507666 的值。

auto nIndex = A >> 5;
auto value = 状态数值[nIndex];

有些状态是取不到5507666的，比如雪恨高级，取的值是 主要数值5，而太极清灵的主要数值5的值是0，所以最终结算的时候，雪恨高级没办法被清除了

**Comment by Aconment** [comment]
大佬牛逼！汇编数据分析啥都会，居然这么有时间摸鱼搞这个

**Comment by WanderingQuantum** [comment]
非常感谢！我已将这些内容加到[页面中](https://www.qqsganalysis.cn/#/%E5%8E%9F%E5%A7%8B%E8%A7%A3%E5%8C%85%E6%95%B0%E6%8D%AE?id=%e5%9f%ba%e7%a1%80%e7%8a%b6%e6%80%81%e6%95%b0%e6%8d%aebasestatusdatatxt%ef%bc%88%e5%88%86%e6%9e%90%e8%80%85%ef%bc%9awu-yafeng%ef%bc%8c%e8%a7%81issue8%ef%bc%89)并标明了出处，如果有修正或补充可以随时提出。
